language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    - ./gradlew build
